
#
#  mcMMO configuration
#  Last updated on 2.1.111-b${BUILD_NUMBER}
#
#####
#
#  Settings for mcMMO in general
###
General:
    Locale: en_US
    MOTD_Enabled: false
    # Send a message to the player when his profile was successfully loaded
    Show_Profile_Loaded: false
    # Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    # Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: false
    # Allow mcMMO to check if a new version is available
    Update_Check: false
    Prefer_Beta: false
    Power_Level_Cap: 0
    # Should mcMMO truncate levels if you lower your max level cap for a skillname
    TruncateSkills: false
    # Should mcMMO print out debug messages?
    Verbose_Logging: false
    # Should mcMMO over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true
    # Play level-up sounds
    LevelUp_Sounds: false
    # This should fix blocks being broken client side, but not server-side.
    # Enable to refresh the chunks around a player at the end of Super Breaker,
    # Giga Drill Breaker, and Berserk. Resource intensive for larger servers.
    Refresh_Chunks: false
    Skill_Scaling:
        RetroMode: true
        Skill_Scaling:
            RetroMode_LevelReq_Factor: 10
            RetroMode_XP_Formula_Factor: 1
        # Turning this on will scale mcMMO around 1-1000 with default scaling factor
        # Everything in your config related to skill level requirements, skill level bonuses, etc will be multiplied by 10 when this mode is on
        # This change is purely cosmetic, it retains the old feel of mcMMO where you could level up thousands of times
    RetroMode:
        Enabled: true
    EventInfoOnPlayerJoin: true
    AdminNotifications: true
    AprilFoolsEvent: true
    EventBroadcasts: true
#
#  Settings for the mcMMO scoreboards
###
Scoreboard:
    # Display player's power levels below their names?
    Power_Level_Tags: false
    # Allow players to use "/mcscoreboard keep" to keep the scoreboard up
    Allow_Keep: true
    # Show the /mcstats scoreboard automatically after logging in
    Show_Stats_After_Login: false
    # Show scoreboard tips 5 times. Tips are only displayed once for every login session.
    # Set to 0 to never show these tips.
    Tips_Amount: 5
    # Add some more color on the board :-)
    Rainbows: false
    # Display ability names?
    Ability_Names: true
    # Settings for each type of scoreboard
    # Print: Should the command output be printed in chat?
    # Board: Should the command output be displayed in the scoreboard sidebar?
    # Display_Time: Amount of time (seconds) to display in the sidebar before clearing.
    # To display permanently, use "/mcscoreboard keep" or set to -1
    Types:
        # Settings for /mcrank
        # The sub-options (Print, Board, Display_Time) are the same for each type.
        Rank:
            Print: false
            Board: true
            Display_Time: 15
        # Settings for /mctop
        Top:
            Print: true
            Board: true
            Display_Time: 15
        # Settings for /mcstats
        Stats:
            Print: false
            Board: true
            Display_Time: 15
        # Settings for /inspect
        Inspect:
            Print: false
            Board: true
            Display_Time: 20
        # Settings for /mccooldown
        Cooldown:
            Print: true
            Board: true
            Display_Time: 41
        # Settings for /<skillname> (e.g. /mining, /unarmed)
        # No "print" option is given here; the information will always be displayed in chat.
        # It should also be noted that this display is pretty dang cool.
        Skill:
            Board: true
            Display_Time: 30
            # Should the board be shown when a player levels up, and for how long?
            # It is recommended to NOT have LevelUp_Time be -1, as this may confuse players.
            LevelUp_Board: true
            LevelUp_Time: 5
    Enable: true
    # Set this to true to enable scoreboards
    UseScoreboards: false
Mob_Healthbar:
    # Enabled: Whether or not the feature is enabled at all
    # Display_Type: Per player Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Enabled: false
    Display_Type: HEARTS
    Display_Time: 3
Database_Purging:
    # Amount of time (in hours) to wait between database purging
    # To only run at server start, set to 0
    # To never run, set to -1
    Purge_Interval: 0
    # Any user who hasn't connected in this many months will be purged from the database
    # To never purge old users, set to -1
    Old_User_Cutoff: 6
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
###
Backups:
    Enabled: true
    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true
#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User_Name: UserName
        User_Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
        # This setting is the max simultaneous mysql connections allowed at a time, needs to be
        # high enough to support multiple player logins in quick succession
        MaxConnections:
            Misc: 30
            Load: 30
            Save: 30
        # This setting is the max size of the pool of cached connections that we hold available
        # at any given time
        MaxPoolSize:
            Misc: 10
            Load: 20
            Save: 20
    Server:
        Port: 3306
        Address: localhost
        SSL: true
    Debug: false
#
#  Settings for Hardcore mode
#  Players will not lose stats when their level is below the Level_Threshold
###
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 1.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: false
            Alchemy: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false
    Vampirism:
        Leech_Percentage: 5.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: false
            Alchemy: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false
#
#  Settings for SMP Mods
###
Mods:
    Tool_Mods_Enabled: false
    Armor_Mods_Enabled: false
    Block_Mods_Enabled: false
    Entity_Mods_Enabled: false
#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: false
        Cooldown: 240
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Prevent_Use_Underground: true
        # Attempt to use the bed spawn, if one is available
        Use_Bed_Spawn: true
        Use_Cost: 1
        Recipe_Cost: 5
        Item_Name: FEATHER
        Sound_Enabled: true
    Flux_Pickaxe:
        Enabled: false
        Sound_Enabled: false
#
#  Settings for Parties
###
Party:
    # Amount of time (in hours) to wait between automatically kicking old party members
    # To only run at server start, set to 0
    # To never kick old users, set to -1
    AutoKick_Interval: -1
    # Any user who hasn't connected in this many days will get kicked from their party
    Old_Party_Member_Cutoff: 7
    # Settings for party share modes
    Sharing:
        ExpShare_bonus_base: 1.1
        ExpShare_bonus_increase: 1.05
        ExpShare_bonus_cap: 1.5
        Range: 1.0
    # Party members level up their party by earning individual experience
    # Newly created parties will not immediately have access to all the party features
    # and have to level up the party a bit before they can use them.
    Leveling:
        Level_Cap: 10
        # Uses the regular XP formula but is multiplied by <amount of party members> + <Xp_Curve_Modifier>
        Xp_Curve_Modifier: 3
        Near_Members_Needed: false
        Inform_All_Party_Members_On_LevelUp: false
        Chat_UnlockLevel: 1
        Teleport_UnlockLevel: 2
        Alliance_UnlockLevel: 5
        ItemShare_UnlockLevel: 8
        XpShare_UnlockLevel: 10
    # Maximum size for a party, -1 for infinite
    MaxSize: -1
    # Enable Hurting other players in the same party
    FriendlyFire: false
#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
        Level_Gate_Abilities: true
    Cooldowns:
        Berserk: 240
        Blast_Mining: 60
        Giga_Drill_Breaker: 240
        Green_Terra: 240
        Serrated_Strikes: 240
        Skull_Splitter: 240
        Super_Breaker: 240
        Tree_Feller: 240
    Max_Seconds:
        Berserk: 0
        Blast_Mining: 0
        Giga_Drill_Breaker: 0
        Green_Terra: 0
        Serrated_Strikes: 0
        Skull_Splitter: 0
        Super_Breaker: 0
        Tree_Feller: 0
    Limits:
        Tree_Feller_Threshold: 500
    Tools:
        # Use more tool durability while using abilities. Set Durability_Loss to 0 to disable the extra durability damage.
        Durability_Loss: 1
#
#  Settings for Skills
#  Level cap of 0 for no limit
###
Skills:
    Acrobatics:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Prevent_AFK_Leveling: true
        Max_Tries_At_Same_Location: 2
        Prevent_Dodge_Lightning: false
        # Prevent earning Acrobatics XP a few seconds after teleporting
        XP_After_Teleport_Cooldown: 5
        Level_Cap: 1000
    Alchemy:
        # Allow Hoppers to transfer ingredients and brew Rank 1 Alchemy potions
        Enabled_for_Hoppers: true
        # Prevent Hoppers from transferring ingredients into Brewing Stands
        Prevent_Hopper_Transfer_Ingredients: false
        # Prevent Hoppers from transferring bottles into Brewing Stands
        Prevent_Hopper_Transfer_Bottles: true
        Level_Cap: 1000
    Archery:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 1000
    Axes:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 1000
        Ability_Activation_Level_Gate: 10
    Excavation:
        Level_Cap: 1000
        Ability_Activation_Level_Gate: 10
    Fishing:
        Level_Cap: 1000
        Drops_Enabled: true
        Override_Vanilla_Treasures: false
        # Always catch fish, even when treasure is found
        Extra_Fish: false
        Lure_Modifier: 4.0
    Herbalism:
        Level_Cap: 1000
        Prevent_AFK_Leveling: true
    Mining:
        Level_Cap: 1000
        Detonator_Name: FLINT_AND_STEEL
        Ability_Activation_Level_Gate: 10
    Repair:
        Level_Cap: 1000
        Anvil_Messages: true
        Anvil_Placed_Sounds: false
        Anvil_Use_Sounds: true
        Anvil_Material: EMERALD_BLOCK
        # Ask for a confirmation when a player tries to repair an enchanted item
        Confirm_Required: true
    Salvage:
        Level_Cap: 1000
        Anvil_Messages: false
        Anvil_Placed_Sounds: true
        Anvil_Use_Sounds: true
        Anvil_Material: DIAMOND_BLOCK
        # Ask for a confirmation when a player tries to salvage an enchanted item
        Confirm_Required: true
    Smelting:
        Level_Cap: 1000
    Swords:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 1000
        Ability_Activation_Level_Gate: 10
    Taming:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 1000
        Call_Of_The_Wild:
            # Item_Material: Material of the item needed to summon the pet
            # Item_Amount: Amount of items required to summon the pet
            # Summon_Amount: Amount of pets to summon when using Call Of The Wild
            # Summon_Length: Pets despawn when their summon life length expires
            # Summon_Max_Amount: Maximum amount of pets that can be summoned at the same time
            Wolf:
                Item_Material: BONE
                Item_Amount: 10
                Summon_Amount: 1
                Summon_Length: 240
                Summon_Max_Amount: 10
                Per_Player_Limit: 2
            Ocelot:
                Item_Material: COD
                Item_Amount: 10
                Summon_Amount: 1
                Summon_Length: 240
                Summon_Max_Amount: 10
                Per_Player_Limit: 1
            Horse:
                Item_Material: APPLE
                Item_Amount: 10
                Summon_Amount: 1
                Summon_Length: 240
                Summon_Max_Amount: 10
                Per_Player_Limit: 1
            Range: 40.0
    Unarmed:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 1000
        Block_Cracker:
            SmoothBrick_To_CrackedBrick: false
        # When using Unarmed, picked up items will automatically get moved to a free slot instead of going in the slot
        # of your hand. Should item pickup be disabled when your entire inventory - except for your hand - is full?
        Item_Pickup_Disabled_Full_Inventory: true
        # Any attacks made without a tool, i.e. with one's open hand, a block, etc., will count as unarmed. 
        Items_As_Unarmed: false
        Ability_Activation_Level_Gate: 10
    Woodcutting:
        Tree_Feller_Sounds: false
        Level_Cap: 1000
        Ability_Activation_Level_Gate: 10
Double_Drops:
    Herbalism:
        Beetroots_Ripe: false
        Brown_Mushroom: false
        Cactus: false
        Carrots_Ripe: false
        Cocoa_Ripe: false
        Wheat_Ripe: false
        Melon: false
        Nether_Wart_Ripe: false
        Potatoes_Ripe: false
        Pumpkin: false
        Red_Mushroom: false
        Red_Tulip: false
        Sugar_Cane: false
        Vine: false
        Lily_Pad: false
        Dandelion: false
    Mining:
        Coal_Ore: false
        Diamond_Ore: false
        Emerald_Ore: false
        End_Stone: false
        Glowstone: false
        Gold_Ore: false
        Iron_Ore: false
        Lapis_Ore: false
        Mossy_Cobblestone: false
        Netherrack: false
        Obsidian: false
        Nether_Quartz_Ore: false
        Redstone_Ore: false
        Sandstone: false
        Stone: false
    Woodcutting:
        Acacia_Log: false
        Birch_Log: false
        Dark_Oak_Log: false
        Oak_Log: false
        Jungle_Log: false
        Spruce_Log: false
#
#  Settings for commands
###
Commands:
    Generic:
        # If true, when using partial names in commands mcMMO will try to look for a match from
        # the offline players. Enabling this might slow the server down if there are a lot of offline players.
        Match_OfflinePlayers: false
    Database:
        # Database command cooldown in milliseconds, cannot be changed below the default value. (1750)
        # Prevents players from spamming /mctop or /mcrank
        Player_Cooldown: 1750
    mcmmo:
        Donate_Message: false
    inspect:
        Max_Distance: 30.0
    ptp:
        Cooldown: 120
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Accept_Required: true
        Request_Timeout: 300
        # If true, require players to have a mcmmo.commands.ptp.world.[WorldName] permission
        # to teleport to, from, or within any given world.
        World_Based_Permissions: false
    partychat:
        Chat_Prefix_Format: '[[GREEN]]([[WHITE]]{0}[[GREEN]])'
        Use_Display_Names: true
        Chat_Prefix_Format_Ally: '[[GREEN]](A)[[RESET]]'
    adminchat:
        Chat_Prefix_Format: '[[AQUA]][[[WHITE]]{0}[[AQUA]]]'
        Use_Display_Names: true
    Skills:
        # Turn this off to prevent mcMMO URL links from being sent
        URL_Links: false
#
#  Settings for particles
###
Particles:
    # These settings determine if fireworks should get launched when a player activates/deactivates an ability
    Ability_Activation: false
    Ability_Deactivation: false
    # Determines if the fireworks should be a large ball or a small one
    LargeFireworks: false
    # Use particle effect when these abilities trigger
    Bleed: false
    Dodge: false
    Flux: false
    Greater_Impact: false
    Call_of_the_Wild: false
    # These settings determine if fireworks should get launched when a player levels-up,
    # this will happen by default for every 100 levels.
    LevelUp_Enabled: false
    LevelUp_Tier: 100
#
#  Settings for sounds
###
Sounds:
    # This setting controls the master volume. 1.0 is Max,  0 would be off
    MasterVolume: 1.0
#
#  Settings for Double Drops
###
Bonus_Drops:
    Herbalism:
        Beetroots: false
        Beetroot: false
        Brown_Mushroom: false
        Cactus: false
        Carrots: false
        Carrot: false
        Cocoa: false
        Cocoa_Beans: false
        Wheat: false
        Melon: false
        Melon_Slice: false
        Nether_Wart: false
        Potatoes: false
        Potatoe: false
        Pumpkin: false
        Red_Mushroom: false
        Sugar_Cane: false
        Vine: false
        Lily_Pad: false
        Red_Tulip: false
        White_Tulip: false
        Pink_Tulip: false
        Orange_Tulip: false
        Dandelion: false
        Poppy: false
        Blue_Orchid: false
        Allium: false
        Azure_Bluet: false
        Oxeye_Daisy: false
        Sunflower: false
        Lilac: false
        Rose_Bush: false
        Peony: false
        Lily_Of_The_Valley: true
        Chorus_Fruit: true
        Chorus_Plant: true
    Mining:
        Andesite: false
        Diorite: false
        Granite: false
        Coal_Ore: false
        Coal: false
        Diamond_Ore: false
        Diamond: false
        Emerald_Ore: false
        Emerald: false
        End_Stone: false
        Glowstone: false
        Glowstone_Dust: false
        Gold_Ore: false
        Iron_Ore: false
        Iron_Ingot: false
        Lapis_Ore: false
        Lapis_Lazuli: false
        Mossy_Cobblestone: false
        Netherrack: false
        Obsidian: false
        Nether_Quartz_Ore: false
        Nether_Quartz: false
        Redstone_Ore: false
        Redstone: false
        Sandstone: false
        Stone: false
        Cobblestone: true
    Woodcutting:
        Acacia_Wood: false
        Acacia_Log: false
        Birch_Wood: false
        Birch_Log: false
        Dark_Oak_Wood: false
        Dark_Oak_Log: false
        Oak_Wood: false
        Oak_Log: false
        Jungle_Wood: false
        Jungle_Log: false
        Spruce_Wood: false
        Spruce_Log: false
