# GriefPrevention Flags
# Plugin Version: 5.8.0
# Server Version: git-Paper-"d16a5d88" (MC: 1.15.2)


World Flags:
  world:
    Default Gamemode: survival
    PvP Only In PvP-Flagged Claims: false
    Message To Send When PvP Is Denied: Player vs. player combat is restricted to
      designated areas.
    Send Message On Enter PvP Enabled Claim: true
    Message: PvP is enabled in this claim, be careful
    Send Message On Exit PvP Enabled Claim: false
    ExitMessage: PvP is disabled in this area, you are now safe
    Biomes:
      Blacklist:
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
  world_nether:
    Default Gamemode: survival
    PvP Only In PvP-Flagged Claims: false
    Message To Send When PvP Is Denied: Player vs. player combat is restricted to
      designated areas.
    Send Message On Enter PvP Enabled Claim: true
    Message: PvP is enabled in this claim, be careful
    Send Message On Exit PvP Enabled Claim: false
    ExitMessage: PvP is disabled in this area, you are now safe
    Biomes:
      Blacklist:
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
  world_the_end:
    Default Gamemode: survival
    PvP Only In PvP-Flagged Claims: false
    Message To Send When PvP Is Denied: Player vs. player combat is restricted to
      designated areas.
    Send Message On Enter PvP Enabled Claim: true
    Message: PvP is enabled in this claim, be careful
    Send Message On Exit PvP Enabled Claim: false
    ExitMessage: PvP is disabled in this area, you are now safe
    Biomes:
      Blacklist:
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
  Testworld:
    Default Gamemode: survival
    PvP Only In PvP-Flagged Claims: false
    Message To Send When PvP Is Denied: Player vs. player combat is restricted to
      designated areas.
    Send Message On Enter PvP Enabled Claim: false
    Message: PvP is enabled in this claim, be careful
    Send Message On Exit PvP Enabled Claim: false
    ExitMessage: PvP is disabled in this area, you are now safe
    Biomes:
      Blacklist:
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
