# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 26.12.2019 02:27:01
#  to ChatControl 8.5.0
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologize.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the ChatControl-8.5.0.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/ChatControl/wiki
# 
# -------------------------------------------------------------------------------------------

Anti_Bot:
  Cooldown:
    Rejoin: 0
    Chat_After_Login: 0
    Command_After_Login: 0
  Block_Chat_Until_Moved: false
  Block_Commands_Until_Moved:
  - /afk
  - /me
  Show_Quit_Message_Only_If_Logged: true
  Block_Signs_With_Same_Text: false
  Disallowed_Nicknames:
  - (n+(\W|\d|_)*i+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)
  - nigga
  - nigger
  - porn
  - niga
  - niqqa
  - Auschwits
  - niqqa
  - niggr
  - niqqer
  - nigga
  - n1qq3r
  - nqqr
  - n1qqr
  - niqqr
  - niqqer
  - n1qqer
  - ni99er
  - n1gger
  - n1gger
  - Nickgur
  - Nickger
  - kneeger
  - kneegrr
  - kneegrow
  - niggur
  - niqqur
  - n1ggur
  - n1qqur
Anti_Caps:
  Enabled: false
  Enabled_In_Commands: false
  Commands_To_Apply:
  - /msg
  - /tell
  Points:
    Warn_Set: spam
    Amount: 4 * ({capsPercentage} / 2)
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Warn_If_Caps_Above_Percent: 50
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: false
    Ignore_Duplicate_Characters: false
  Regex_In_Whitelists: false
  Commands:
    Command_Delay: 0
    Limit:
      Period: 10 seconds
      Max_Commands: 30
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 3 - {delay}
    Similar_Percentage_Block: 0
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)
    Whitelist_Works_Like_Blacklist: false
    Whitelist_Similarity:
    - /tell
    - /pm
    - /t
    - /w
    - /r
    - /kc
    - /k
    - /kittycannon
    Whitelist_Delay:
    - /spawn
    - /hello
    - /kittycannon
    - /k
    - /kc
    Handle_As_Chat:
    - /me
    - /f
  Chat:
    Message_Delay: 0
    Limit:
      Period: 10 seconds
      Max_Messages: 8
      Points:
        Warn_Set: fastmessages
        Amount: 3
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 3 - {delay}
    Similar_Percentage_Block: 0
    Similarity_Message_Check_Count: 3
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)
    Whitelist_Similarity:
    - hello
    - hey
    - home
    - tpa
    - tphere
    - tpyes
    - tpcancel
    - scream
    - poop
    - foxnoises
    - hat
    - craft
    - kittycannon
    - kc
    - colors
    - cosmetics
    - heads
    - warp
    - skull
    - nick
    - poke
    - cuddle
    - pet
    - kiss
    - lick
    - slap
    - f
    - x
    - cry
    Whitelist_Delay:
    - test
    Parrot:
      Enabled: false
      Delay: 20 ticks
      Minimum_Similarity: 85
      Whitelist:
      - hello
      - hey
Grammar:
  Insert_Dot:
    Enabled: false
    Min_Message_Length: 4
  Capitalize:
    Enabled: false
    Min_Message_Length: 5
  Lowercase_Second:
    Enabled: false
Clear:
  Broadcast: false
  Do_Not_Clear_For_Staff: true
  Console_Lines: 300
Mute:
  Broadcast: false
  Prevent:
    Writing_Books: false
    Placing_Signs: true
  Silence:
    Join_Messages: false
    Quit_Messages: false
    Death_Messages: false
  Disabled_Commands:
  - /me
  - /tell
  - /msg
  - /r
  - /w
  Apply_Limits_For_Essentials_Mute: true
Newcomer:
  Threshold: 0 minutes
  Worlds:
  - '*'
  Restrict_Chat:
    Enabled: false
    Whitelist: []
  Restrict_Seeing_Chat:
    Enabled: false
  Restrict_Commands:
    Enabled: false
    Whitelist:
    - /login
    - /l
    - /register
    - /reg
    - /helpop
    - /help
    - /?
    Blacklist: false
  Warn_Points_Multiplier: 1.0
Announcer:
  Bungee: false
  Ignore_Self: false
  Log_To_Console: false
  Sound: ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
Admin_Chat:
  Bungee: false
  Log_To_Console: false
  Write_To_File: false
  Discord_Channel: admin
  Shortcut: none
Bungee_Chat:
  Enabled_By_Default: false
  Log_To_Console: false
  Write_To_File: false
  Discord_Channel: global
  Shortcut: '!'
Private_Messages:
  Enabled: false
  Bungee: false
  Deny_Message_Self: false
  Register_Reply_To_Self: true
  Register_Reply_To_Receiver: true
  Toast:
    Enabled: false
    Format: '&6[{sender} &8-> &6you]{dynamic_spaces}&7{message}'
  Auto_Start:
    Enabled: false
    Prefix: '@'
    End: exit
    Start_For_Empty_Tell_Command: false
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
  Deep_Search: true
  Reply_Change_Timeout: 3 seconds
Ignore:
  Enabled: false
  Aliases:
  - ignore
  - ign
  Chat: true
  Private_Messages: true
Me:
  Enabled: false
  Aliases:
  - me
  - shout
  - status
  Bungee: false
Packets:
  Enabled: true
  Tab_Complete:
    Hide_Vanished_Players:
      Enabled: true
      Maximum_Length: 30
    Enabled: false
    Only_In_Commands: true
    Require_Arguments: 1
    Require_Length: -1
  Replace_Unicode_In_Books: true
Rules:
  Verbose: false
  Bungee: false
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
Console_Filter:
  Enabled: false
  Filter_System_Out: false
  Log: false
  Filter_Console_Messages:
  - Reached end of stream for
  - Connection reset
Sound_Notify:
  Enabled: true
  Cooldown: 2 seconds
  Require_Afk: false
  Require_Prefix: '@'
  Sound: ENTITY_FIREWORK_LAUNCH, 10F, 1.5F
  Color: '&4'
  Enabled_In_Commands:
  - /msg
  - /tell
  - /t
  - /w
  - /r
  Use_Sender_Group_Color: false
Groups:
  Enabled: false
  List:
    vip:
      Message_Delay: 0
      Command_Delay: 0
Points:
  Enabled: false
  Smart_Warnings: false
  Reset_Task:
    Repeat_Every_Seconds: 20
    Remove:
      global: 5
      spam: 1
  Warn_Sets:
    global:
      '5':
      - warn &7Please obey the &2rules &7otherwise you will be &4punished&7.
      '15':
      - |-
        warn &c**** &lHey &c{player} ****
         &7-> &cThis is your &6final &cwarning!
      '30':
      - kick {player} &cKicked for breaking the rules
    swear:
      '4':
      - warn &cYou have received first warning for swearing.
      '6':
      - warn &cPlease do not swear, otherwise an action will be taken!
      '8':
      - kick {player} &cInappropriate language (last warning)
    spam:
      '4':
      - warn &cPlease do not act like spammer.
      '8':
      - warn &cPlease do not spam, otherwise you will be banned.
      '12':
      - kick {player} &cSpamming the chat (last warning)
      '16':
      - banip {player} Spamming the chat
    fastmessages:
      '6':
      - warn &cPlease slow down chat messages.
      '10':
      - warn &cSlow down chat, otherwise you will be banned.
      '14':
      - kick {player} &cSlow down chat (last warning)
Variables:
  Custom_Enabled: false
  Replace_In_Custom: true
  Replace_Own_In_Custom: false
  Vault:
    Multi_Prefix: false
    Multi_Suffix: false
Writer:
  Enabled: false
  Ignore_Players:
  - ignoredAdmin
  Commands:
  - /me
  - /msg
  - /m
  - /tell
  - /t
  - /reply
  - /r
  - /mail
Motd:
  Enabled: false
  Delay_Ticks: 2
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&8*--------------------------------------------------*'
  - '&fHello {player}, we kindly welcome you to &e{server_name}&f and wish you great
    experience :)'
  - ''
  - '&6Version: &f{nms_version}'
  - '&6Changelog:'
  - ' &7- &fAdded ChatControl Pro plugin'
  - ''
  - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
  - '&8*--------------------------------------------------*'
  Message_First_Time: []
  Message_Newcomer: []
  Command_Aliases:
  - motd
  - welcome
Spy:
  Enabled: true
  Command_Aliases:
  - spy
  - socialspy
  Format: '&8[&5spy&8] &7{player}: &7{message}'
  Format_PM: '&8[&5spy&8] &7[{player}] -> [{receiver}]: &7{message}'
  Channel_Prefix: '&8[&5spy&8] '
  Command_List_Works_Like_Blacklist: false
  McMMO: true
  Log_McMMO: false
  Books: true
  Signs: false
  Command_List:
  - /tell
  - /msg
  - /t
  - /whisper
  - /r
  - /reply
  Bungee: true
  Format_Sign: '&8SPY: &7 [{location}] {player} placed a sign: [&8{text}&7]'
  Format_TownyChat: '&8[&5spy&8] &7[{townychat_channel}] &7{player}: &7{message}'
MySQL:
  Enabled: false
  Aggressive: false
  Connection:
    Host: localhost
    Database: minecraft
    Port: '3306'
    User: ''
    Password: ''
    Table_Prefix: ChatControl_
    Connector_Advanced: jdbc:mysql://{host}:{port}/{database}?autoReconnect=true
Listener_Priority:
  Checker: HIGHEST
  Formatter: HIGHEST
  Signs: HIGHEST
Command_Aliases:
- chatcontrol
- chc
- cc
Locale: en
Prefix: '&8[&3Chat&8]&7 '
Server_Name: default
Translate_Diacritical_Marks: true
Clear_Data_If_Inactive: 10 days
Regex_Timeout_Milis: 100
Log_Lag_Over_Milis: 100
Silent_Startup: false
Regex_Strip_Colors: true
Reset_Cache_On_Quit: false
Enforce_New_Line: true
Notify_Updates: false
Notify_Promotions: false
Debug: []
Serialization: ''
Version: 24
Toggle_Broadcast:
  Enabled: false
  Aliases:
  - togglebroadcast
  - togglebc
  - toggletm
  - ignorebroadcast
  - ignorebc
  - ignoretm
  - nobroadcast
  - nobc
  - notc
Color_Menu:
  Title: Chat Color & Decoration
  Icon:
    No_Permission: BARRIER
    Reset_Decoration: WHITE_CARPET
    Reset_All: FEATHER
    Color: WHITE_SHULKER_BOX
    Decoration: WHITE_CARPET
Bungee_Server_Name: undefined
BungeeCord:
  Enabled: false
  Prefix: '&8[&5Bungee/{server_name}&8] &7'
Regex_Unicode: true
