error message: "&cYou cannot place signs while muted."

materials:
- SIGN
- SIGN_POST
- WALL_SIGN
- ACACIA_SIGN
- ACACIA_WALL_SIGN
- BIRCH_SIGN
- BIRCH_WALL_SIGN
- DARK_OAK_SIGN
- DARK_OAK_WALL_SIGN
- JUNGLE_SIGN
- JUNGLE_WALL_SIGN
- LEGACY_SIGN
- LEGACY_SIGN_POST
- LEGACY_WALL_SIGN
- OAK_SIGN
- OAK_WALL_SIGN
- SPRUCE_SIGN
- SPRUCE_WALL_SIGN

