messages:
  prefix: "&9&lCyna&f&lGen &6&l>&f"
  cooldowned-command: "%prefix% &fCommand Cooldown: %x%"
  warmup-already: "%prefix% &cYou are already in warmup !"
cooldowned-commands:
  wild:
    command: "wild"
    delay-in-second: 600
  f:
    command: "f"
    delay-in-second: 60
  x:
    command: "x"
    delay-in-second: 60
  cry:
    command: "cry"
    delay-in-second: 60
  poop:
    command: "poop"
    delay-in-second: 60
  foxnoises:
    command: "foxnoises"
    delay-in-second: 120
  scream:
    command: "scream"
    delay-in-second: 120
  eatshit:
    command: "eatshit"
    delay-in-second: 3000
  fart:
    command: "fart"
    delay-in-second: 60
  givepet:
    command: "givepet"
    delay-in-second: 300
warmuped-commands:
  fhomesrfe:
    command: "fhomesrfe"
    delay-in-second: 10
    warmuped-oncommand: "Wait 10 seconds for your teleportation!"
    warmuped-onmove: "Teleportation cancelled! You have moved"
