# 
#      db      `7MM"""Mq.  `7MMM.     ,MMF'#
#     ;MM:       MM   `MM.   MMMb    dPMM  #
#    ,V^MM.      MM   ,M9    M YM   ,M MM  #
#   ,M  `MM      MMmmdM9     M  Mb  M' MM  #
#   AbmmmqMA     MM  YM.     M  YM.P'  MM  #
#  A'     VML    MM   `Mb.   M  `YM'   MM  #
AutoPrice:
  example1:
    price: 200.0
    extendTime: 2d
    maxRentTime: 7d
    autoPriceCalculation: static
  example2:
    price: 2.0
    extendTime: 12h
    maxRentTime: 2d
    autoPriceCalculation: per_m2
  example3:
    price: 0.05
    extendTime: 7d
    maxRentTime: 30d
    autoPriceCalculation: per_m3
DefaultAutoprice:
  price: 2.0
  extendTime: 1d
  maxRentTime: 7d
  autoPriceCalculation: per_m2
Limits:
  group1:
    total: 1
    Default: 1
    starter: 1
    small: 1
    medium: 0
    large: 0
    shop: 1
    VIP: 1
    donator: 1
  examplegroup2:
    total: 1
    Default: -1
    starter: 1
    small: 2
    medium: 1
    large: 1
    shop: 1
  examplegroup3:
    total: -1
    Default: -1
    starter: 1
    small: 2
    medium: 2
    large: 2
    shop: 2
RegionKinds:
  activateRegionKindPermissions: false
PriceFormatting:
  locale: US
  minimumFractionDigits: 2
  maximumFractionDigits: 2
  minimumIntegerDigits: 1
Other:
  userResetCooldown: 7d
  TeleportAfterSellRegionBought: false
  TeleportAfterRentRegionBought: false
  TeleportAfterRentRegionExtend: false
  TeleportAfterContractRegionBought: false
  TeleportAfterRegionBoughtCountdown: false
  SendRentRegionExpirationWarning: true
  RentRegionExpirationWarningTime: 5d
  SendContractRegionExtendMessage: false
  SignAndResetUpdateInterval: 600
  DateTimeFormat: dd.MM.yyyy HH:mm
  CompleteRegionsOnTabComplete: false
  TeleporterTimer: 2
  RegionInfoParticleBorder: true
  AllowRegionfinderTeleportToBuySign: false
  RemoveEntitiesOnRegionBlockReset: false
  Sendstats: true
  Language: en
  RemoveEntitiesOnRegionRestore: true
SignClickActions:
  RightClickNotSneakCmd: buyaction
  RightClickSneakCmd: arm sellback %regionid%
  LeftClickNotSneakCmd: arm info %regionid%
  LeftClickSneakCmd: arm info %regionid%
Subregions:
  SubregionAutoReset: true
  deleteSubregionsOnParentRegionUnsell: false
  deleteSubregionsOnParentRegionBlockReset: false
  allowParentRegionOwnersBuildOnSubregions: true
  SubregionInactivityReset: true
  AllowSubregionUserRestore: false
  SubregionAutoRestore: false
  deleteSubregionsOnParentRegionRestore: false
Reselling:
  Offers:
    OfferTimeOut: 30
GUI:
  RegionOwnerItem: ENDER_CHEST
  RegionMemberItem: CHEST
  RegionFinderItem: COMPASS
  GoBackItem: OAK_DOOR
  WarningYesItem: MELON
  WarningNoItem: REDSTONE_BLOCK
  TPItem: ENDER_PEARL
  SellRegionItem: DIAMOND
  ResetItem: TNT
  ExtendItem: CLOCK
  InfoItem: BOOK
  PromoteMemberToOwnerItem: LADDER
  RemoveMemberItem: LAVA_BUCKET
  FillItem: GRAY_STAINED_GLASS_PANE
  ContractItem: WRITABLE_BOOK
  SubRegionItem: GRASS_BLOCK
  TeleportToSignItem: OAK_SIGN
  TeleportToRegionItem: GRASS_BLOCK
  DeleteItem: BARRIER
  NextPageItem: ARROW
  PrevPageItem: ARROW
  HotelSettingItem: RED_BED
  UnsellItem: NAME_TAG
  DisplayRegionOwnerButton: true
  DisplayRegionMemberButton: true
  DisplayRegionFinderButton: true
  FlageditorItem: BANNER
  FlagItem: SIGN
  FlagSettingsSelectedItem: EMERALD_BLOCK
  FlagSettingsNotSelectedItem: REDSTONE_BLOCK
  FlagGroupSelectedItem: EMERALD_BLOCK
  FlagGroupNotSelectedItem: REDSTONE_BLOCK
  FlagRemoveItem: BARRIER
  FlagUserInputItem: WRITABLE_BOOK
  FlageditorResetItem: TNT
Version: 2.14
SignLinkingMode:
  regionblacklist:
    world:
    - blacklistedTestRegionInWorld1
    - blacklistedTestRegionInWorld2
    world_nether:
    - blacklistedTestRegionInWorld_nether1
    - blacklistedTestRegionInWorld_nether2
    world_the_end:
    - anotherBlacklistedRegion
DefaultInactivityExpiration:
  resetAfter: none
  takeOverAfter: none
InactivityExpiration:
  examplegroup1:
    resetAfter: 30d
    takeOverAfter: 20d
  examplegroup2:
    resetAfter: 60d
    takeOverAfter: 50d
  examplegroup3:
    resetAfter: none
    takeOverAfter: none
FlagGroups:
  enabled: true
Backups:
  createBackupOnRegionRestore: true
  createBackupOnRegionUnsell: true
