# -----------------------------------------------------
# Plan Bukkit Configuration file
# More information about each setting:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bukkit-Configuration
# -----------------------------------------------------
Server:
    ServerName: 'Plan'
# -----------------------------------------------------
# More information about Locale
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Localization
# -----------------------------------------------------
Plugin:
    Logging:
        # More information about Locale
        # https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Localization
        Locale: default
        Create_new_locale_file_on_next_enable: false
        Debug: false
        Dev: false
        Delete_logs_after_days: 7
    Update_notifications:
        Notify_about_DEV_releases: false
        # Display update notification on the website
        Check_for_updates: true
    Configuration:
        Allow_proxy_to_manage_settings: true
# -----------------------------------------------------
# Supported databases: SQLite, H2, MySQL
# -----------------------------------------------------
Database:
    Type: SQLite
    MySQL:
        Host: localhost
        Port: [REDACTED]
        User: [REDACTED]
        Password: [REDACTED]
        Database: Plan
        # Launch options to append after driver address, for example
        Launch_options: "?rewriteBatchedStatements=true&useSSL=false"
# -----------------------------------------------------
# More information about SSL Certificate Settings:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
# -----------------------------------------------------
Webserver:
    Port: 8144
    Security:
        SSL_certificate:
            Alias: 'alias'
            KeyStore_path: 'SSLCertificate.keystore'
            Key_pass: 'default'
            Store_pass: 'default'
        # Cross-Origin Resource Sharing (Requests from non-Plan web pages)
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
        CORS:
            Allow_origin: "*"
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Disable_Webserver: false
    External_Webserver_address: "https://www.example.address"
    Alternative_IP: false
        # %port% is replaced automatically with Webserver.Port
        Address: your.domain.here:%port%
# -----------------------------------------------------
Data_gathering:
    Geolocations: false
    Commands:
        Log_unknown: false
        Log_aliases_as_main_command: true
    Ping: false
    # Please accept the EULA to download GeoLite2 IP-Country Database
    # https://www.maxmind.com/en/geolite2/eula
    Accept_GeoLite2_EULA: false
# -----------------------------------------------------
# Supported time units: MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
# -----------------------------------------------------
Time:
    Thresholds:
        # How many minutes player has to stay still to be considered AFK
        AFK_threshold: 5
            Unit: MINUTES
        # Activity Index considers last 3 weeks and uses these thresholds in the calculation
        # The index is a number from 0 to 5.
        # These numbers were calibrated with data of 250 players (Small sample size).
        Activity_index:
            # Minutes a player should play per week to be considered active
            Playtime_threshold: 30
                Unit: MINUTES
        Remove_inactive_player_data_after: 180
            Unit: DAYS
        # Includes players online, tps and performance time series
        Remove_time_series_data_after: 90
            Unit: DAYS
        Remove_ping_data_after: 14
            Unit: DAYS
        Remove_disabled_extension_data_after: 2
            Unit: DAYS
    Periodic_tasks:
        Extension_data_refresh_every: 1
            Unit: HOURS
        Check_DB_for_server_config_files_every: 1
            Unit: HOURS
        Clean_Database_every: 1
            Unit: HOURS
    Delays:
        Ping_server_enable_delay: 300
            Unit: SECONDS
        Ping_player_join_delay: 30
            Unit: SECONDS
        Wait_for_DB_Transactions_on_disable: 20
            Unit: SECONDS
# -----------------------------------------------------
Display_options:
    # More information about Themes:
    # https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Themes
    Theme: Default
    Sessions:
        Show_on_page: 50
        # By Default World playtime pie is ordered alphabetically.
        # Colors will be determined alphabetically in any case.
        Order_world_pies_by_percentage: false
    Players_table:
        Show_on_server_page: 2500
        Show_on_players_page: 25000
    Graphs:
        Show_gaps_in_data: false
        TPS:
            High_threshold: 18
            Medium_threshold: 10
        Disk_space:
            High_threshold: 500
            Medium_threshold: 100
    Command_colors:
        Main: '&2'
        Secondary: '&7'
        Highlight: '&f'
    Open_player_links_in_new_tab: false
# -----------------------------------------------------
Formatting:
    # Dates settings use Java SimpleDateFormat.
    # You can find the patterns & examples here:
    # https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
    Dates:
        Full: 'MMM d YYYY, HH:mm:ss'
        NoSeconds: 'MMM d YYYY, HH:mm'
        JustClock: 'HH:mm:ss'
        # RecentDays replaces date with Today, Yesterday, Wednesday etc.
        Show_recent_day_names: true
            # Non-regex pattern to replace
            DatePattern: 'MMM d YYYY'
        # TimeZone Option uses format 'GMT+2' or 'GMT-04:30'
        # Other valid options are 'server' and 'UTC'
        TimeZone: server
    Decimal_points: '#.##'
    Time_amount:
        Year: '1 year, '
        Years: '%years% years, '
        Month: '1 month, '
        Months: '%months% months, '
        Day: '1d '
        Days: '%days%d '
        Hours: '%hours%h '
        Minutes: '%minutes%m '
        Seconds: '%seconds%s'
        Zero: '0s'
# -----------------------------------------------------
# World aliases can be used to rename worlds and to combine multiple worlds into a group.
# -----------------------------------------------------
World_aliases:
    world: world
    world_nether: world_nether
    world_the_end: world_the_end
    Shop: Shop
    Testworld: Testworld
# -----------------------------------------------------
# These settings will make Plan write .js, .css, .json and .html files to some location on disk.
# Relative path will render to /plugins/Plan/path
# Make sure user running the server has write permissions to the path.
# On networks export is disabled on Bukkit/Sponge servers.
# -----------------------------------------------------
Export:
    HTML_Export_path: 'Analysis Results'
    Parts:
        # Player pages/JSON are only written on join/leave.
        Player_pages: false
        Players_page: false
        Server_page: false
        Player_JSON: false
        Server_JSON: false
    JSON_Export_path: 'Raw JSON'
    # All player pages/JSON can be exported by using /plan m export players
    Export_player_on_login_and_logout: false
    # If there are multiple servers the period is divided evenly to avoid export of all servers at once
    # Also affects Players page export
    Server_refresh_period: 20
        Unit: MINUTES
# -----------------------------------------------------
# These settings affect Plugin data integration.
# If a plugin is causing issues the integration can be disabled by setting Plugin_name.Enabled: false
# -----------------------------------------------------
Plugins:
    AdvancedAntiCheat:
        Enabled: false
    AntiCheat:
        Enabled: false
    Buycraft:
        # http://help.buycraft.net/article/36-where-to-find-the-secret-key
        Secret: "-"
    CoreProtect:
        Enabled: true
    DiscordSRV:
        Enabled: false
    Economy (Essentials Economy):
        Enabled: true
    Economy (Vault):
        Enabled: true
    Essentials:
        Enabled: true
    Factions:
        HideFactions: APF_NEWLINE - ExampleFaction
    GriefPrevention:
        Enabled: true
    Litebans:
        Enabled: true
    LuckPerms:
        Enabled: false
    MCMMO:
        Enabled: true
    SuperbVote:
        Enabled: true
    Towny:
        HideTowns: APF_NEWLINE - ExampleTown
    ViaVersion:
        Enabled: false
    mcMMO:
        Enabled: true
    nuVotifier:
        Enabled: true
