connection_throttle_limit: 3
online_mode: true
log_commands: false
network_compression_threshold: 64
listeners:
- query_port: 25580
  motd: |-
    &1                     &9Cyna&f&lgen&r | &a&lSMP
                    &e&osite.cynagen.xyz
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: main
  ping_passthrough: true
  priorities:
  - main
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 40
  tab_size: 60
  force_default_server: true
connection_throttle: 4000
groups:
  Kyrobi:
  - admin
log_pings: false
ip_forward: true
prevent_proxy_connections: false
forge_support: false
stats: [REDACTED]
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - notify.send
  - notify.receive
servers:
  main:
    motd: '&1Main survival server'
    address: [REDACTED]
    restricted: false
  Build:
    motd: '&1Build server'
    address: [REDACTED]
    restricted: false
  Private:
    motd: '&1Private server'
    address: [REDACTED]
    restricted: false
player_limit: 80
