# This is the BeSocial config. For message editing, see below the 'enable' part.
enablePlugin: true
enableCommand:
  highfive: true
  handshake: true
  beso: true
  hug: true
  cuddle: true
  kiss: true
  lick: true
  poke: true
  pet: true
  slap: true
  slice: false
messages:
  prefix: '&9&lCyna&f&lGen'
  sender:
    error:
      senderNotMember: '&cI''m sorry, but you can''t do that. You''re not a member
        of the BeSocial program.'
      targetNotMember: '&cI''m sorry, but you can''t do that. This player isn''t a
        member of the BeSocial program.'
      targetOffline: '&cThat player is not online right now.'
      selfSocial:
        highfive: '&dWell done!'
        handshake: '&dBeing a gentleman is hard work.'
        hug: '&dYou hugged &5yourself &d! Now try hugging someone else.'
        cuddle: '&cYou can''t cuddle yourself. Try cuddling someone else. Stop doing
          the impossible'
        kiss: '&cQuite narcissistic, huh?'
        lick: '&dYou licked &5yourself &d! &r&o&7(That''s disgusting...)'
        poke: '&dYou poked &5yourself &d! (That moment when you have nothing else
          better to do)'
        pet: '&cLOL! Imagine trying to pet yourself.'
        slap: '&cDon''t slap yourself! Everything is fine...for now'
        slice: '&5Hecc you! Self harm isn''t allowed.'
    success:
      highfive: '&dYou gave &5%target &da highfive!'
      handshake: '&dYou give &5%target &da handshake.'
      hug: '&d%sender hugged &5%target &d!'
      cuddle: '&d%sender cuddled &5%target &d!'
      kiss: '&d%sender kissed &5%target &d!'
      lick: '&d%sender licked &5%target &d!'
      poke: '&d%sender forcefully poked &5%target &d!'
      pet: '&d%sender pets &5%target &d!'
      slap: '&4%sender fricken slapped &5%target &4!'
      slice: '&5%sender &4sliced &5%target &4!'
  target:
    success:
      highfive: '&5%sender &dgave you a highfive!'
      handshake: '&5%sender &dgives you a handshake.'
      hug: '&5%sender &dhugged you!'
      cuddle: '&5%sender &dcuddled you!'
      kiss: '&5%sender &dkissed you!'
      lick: '&5%sender &dlicked you!'
      poke: '&5%sender &dpoked you!'
      pet: '&5%sender &dpetted you!'
      slap: '&5%sender &4slapped you!'
      slice: '&5%sender &4sliced you!'
  special:
    leaveBeSocial: '&cIt''s a pity you leave the BeSocial program. We will miss you.'
    leaveBeSocial2: '&cIf you want to join the program again, please ask an admin.'
    error: '&cERROR!'
  admin:
    notAnAdmin: '&cYou can''t do that. Why? Because you don''t have the &r&o&cbesocial.admin
      &r&cpermission.'
    userBlocked: '&2The player &a%player &2was banned from the BeSocial program.'
    userFreed: '&2The player &a%player &2can now use the BeSocial program''s commands.'
    listReloaded: '&2Playerlist sucessfully reloaded.'
    listSaved: '&2Playerlist sucessfully saved.'
    specifyUser: '&cYou have to specify an user!'
    success: '&2Operation successful.'
